services:
    prestashop:
        image: prestashop/prestashop:8.1.4
        container_name: prestashop
        ports: 
            - "8080:80"
        environment:
            DB_SERVER: mysql 
            DB_NAME: prestashop 
            DB_USER: root 
            DB_PASSWORD: root 
            PS_INSTALL_AUTO: 1 
            PS_DOMAIN: localhost:8080 
            PS_FOLDER_ADMIN: admin-dev
            PS_FOLDER_INSTALL: install-dev 
        volumes:
            - ./modules:/var/www/html/modules
            - prestashop_data:/var/www/html

    mysql:
        image: mysql:5.7
        platform: linux/amd64
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: prestashop
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        image: adminer
        platform: linux/amd64
        container_name: adminer
        ports:
        - "8081:8080"

volumes:
    mysql_data:
    prestashop_data: